### ISSUE TITLE
pip install twitter_markov errors out

### ISSUE THREAD

**Issue by TheNathanBlack** [fitnr/twitter_markov#1]
When I attempt to install twitter_markov via pip install it errors out with the following error message:

```
Downloading/unpacking wordfilter (from twitter-markov)
  Could not find any downloads that satisfy the requirement wordfilter (from twitter-markov)
  Some externally hosted files were ignored (use --allow-external wordfilter to allow).
Cleaning up...
No distributions at all found for wordfilter (from twitter-markov)
Storing debug log for failure in /Users/nathan/.pip/pip.log
```
if I `--allow-external wordfilter` it fails with the same message.

**Comment by fitnr** [comment]
Sorry about that, the wordfilter python port is a work in progress, and should be fixed soon. I'm not sure why `--allow-external` isn't working. You should be able to [manually install it](https://github.com/fitnr/wordfilter/releases/tag/0.1.7), and then `pip install twitter_markov` will work.

**Comment by fitnr** [comment]
This should be fixed!

**Comment by TheNathanBlack** [comment]
That fixed it! Thanks!
