### ISSUE TITLE
After upgrading to ubuntu 16.04, no longer recognizes bots.yaml

### ISSUE THREAD

**Issue by andrew-wilcox** [fitnr/twitter_markov#10]
I upgraded to ubuntu 16.04 and I was wondering if you had any insight as to why my script wasn't working anymore. It seems it just doesn't recognize the config file at all. Here are both the config file I'm using and the command I'm running, as well as the error output:

```
/usr/local/bin/twittermarkov -c /usr/local/bin/twitterbots/pastebin_ebooks/bots.yaml -u pastebin_ebooks -n -v tweet

Traceback (most recent call last):
  File "/usr/local/bin/twittermarkov", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/twitter_markov/cli.py", line 73, in main
    func(**argdict)
  File "/usr/local/lib/python2.7/dist-packages/twitter_markov/cli.py", line 80, in tweet_func
    tm = TwitterMarkov(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/twitter_markov/twitter_markov.py", line 49, in __init__
    self.api = tbu.API(screen_name=screen_name, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/twitter_bot_utils/api.py", line 83, in __init__
    raise ValueError("Incomplete config. Missing {}".format(missing))
ValueError: Incomplete config. Missing ['consumer_key', 'consumer_secret', 'key', 'secret']
```
## bots.yaml:

```
apps:
    pastebin_ebooks:
        consumer_key: [c_key]
        consumer_secret: [c_secret]

users:
    pastebin_ebooks:
        key: [key]
        secret: [secret]

        app: pastebin_ebooks

        corpus: /usr/local/bin/twitterbots/pastebin_ebooks/corpus.txt
```

I've also tried it with a .json file (after seeing the "missing {}" message, to receive the exact same error)

**Comment by fitnr** [comment]
I'm a little mystified about what could be broken. The version of Ubuntu shouldn't really matter.

Do the permissions on the `bots.yaml` allow reading by your user?

Can you try two things?

Run the following in the Python interpreter:
```python
from twitter_bot_utils import confighelper
confighelper.configure('pastebin_ebooks', '/usr/local/bin/twitterbots/pastebin_ebooks/bots.yaml')
```
The result should be something like
```
{'key': 'key', 'secret': 'secret', 'consumer_secret': 'c_secret', 'app': 'pastebin_ebooks', 'consumer_key': 'c_key', 'corpus': '/usr/local/bin/twitterbots/pastebin_ebooks/corpus.txt'}
```

Next, clone the package and run `python setup.py test` to run all of the tests.

**Comment by andrew-wilcox** [comment]
Thanks for looking into this, I agree it's very strange.

Full permissions on bots.yaml does not change the output.

Running those commands in the interpreter as you said results in a package exactly like you described, with my keys as I have them defined in bots.yaml.

The tests all run and pass fine when I run them, I can attach that output if you like, but they all pass without issue.

I'm a bit stumped here, as well...

**Comment by mattbk** [comment]
Same issue here, did you find a solution?

**Comment by Reapette** [comment]
@mattbk 
Had something like this on one of the machines I'm playing with this at (debian)

solved by specifying -c /path/to/config.yaml -u TwitterAcc on command line. 
Dunno if it helps on ubuntu but worth a try
