### ISSUE TITLE
Reply To One

### ISSUE THREAD

**Issue by BrekiTomasson** [fitnr/twitter_markov#4]
Last question, promise. :)

Any way of getting the --reply command to just reply to the one latest unanswered tweet? I'm trying to emulate a "natural" posting schedule using random intervals, post windows, cron jobs, etc, and having a block of multiple replies the same minute looks strange.

**Comment by fitnr** [comment]
I'm a hesitant to add such a specific flag to the cli. I have a little trouble imagining that it will be widely useful, if for no other reason than that _ebooks bots don't get a lot of mentions.

The setting I would consider adding would be something like "reply_probability", a dice roll run before the bot replies to any given mention.

This is also something that would be fairly straightforward to script.:
````python
from twitter_markov import TwitterMarkov

# or set these with sys.argv or argparse
USER = 'foo'
CORPUS = 'tweets.txt'
CONFIG = 'path/bots.yaml'

tm = TwitterMarkov(USER, corpus=CORPUS, config_file=CONFIG)

# do something to select a mention
mentions = tm.api.mentions_timeline(count=5, since_id=tm.api.last_reply)
mention = mentions[0]

# reply
tm.reply(mention)
````

Ask as many questions as you need! I'm happy to make the module more useful.

**Comment by BrekiTomasson** [comment]
Clever solution! Thanks! Only problem I can see is that it doesn't fail gracefully if there are no tweets to reply to:

`´`
Traceback (most recent call last):
  File "replyOne.py", line 12, in <module>
    mention = mentions[0]
IndexError: list index out of range
```

The way I'm doing it right now is that I'm running a cron job every minute between 9 in the morning and 10 in the evening that calls a bash script. The bash script rolls a 100-sided dice, where if the number is below 15 it does a reply, and if it's above 90 it posts a new tweet - kind of to emulate a more "natural" posting rhythm that resembles what it would be like if it were an actual human.

**Comment by fitnr** [comment]
Just add some [error handling](https://wiki.python.org/moin/HandlingExceptions):
```python
import tweepy.error
# ...
try:
    tm.reply(mentions[0])
except IndexError:
    print('No mentions found')
except tweepy.error.TweepError as e:
   print('Got an error from twitter:', e.code, e.message)
```

Replace the `print` calls with whatever you want to do when an error occurs.
