### ISSUE TITLE
Ending reply chains

### ISSUE THREAD

**Issue by BrekiTomasson** [fitnr/twitter_markov#5]
Just out of curiosity, have you put any logic into the bot that will end a reply chain after a specific time if two of these bots reply to each other?

**Comment by fitnr** [comment]
No, that doesn't exist within the bot. However, it would be straightforward to add a check in Python using the Tweepy API.

**Comment by BrekiTomasson** [comment]
Got any suggestions for how? My Python skills are just barely good enough to get this working as is. :)

**Comment by fitnr** [comment]
This should start getting you there. Each `TwitterMarkov` instance comes with an `api`, which is a full-fledged tweepy API.


````python
from twitter_markov import TwitterMarkov

SCREEN_NAME = 'yourbotnamehere'
CORPUS = 'corpus.txt'


def get_reply_chain(api, status, max_depth=5):
    '''Construct a list of statuses in a Ywitter conversation chain, looking back <max_depth> steps.'''
    replychain = [status]

    # build a chain of the last <depth> replies
    for _ in range(max_depth - 1):
        if replychain[-1].in_reply_to_status_id:
            parent = api.get_status(replychain[-1].in_reply_to_status_id, include_entities=False)
            replychain.append(parent)
        else:
            break

    return replychain


def main():
    max_depth = sys.argv[1]
    # Assumes a bots.yaml file in ~/ or ~/bots
    tm = TwitterMarkov(SCREEN_NAME, CORPUS)

    mentions = tm.api.mentions_timeline(since_id=tm.api.last_reply)

    for status in mentions:
        if status.in_reply_to_screen_name == SCREEN_NAME:
            replychain = get_reply_chain(tm.api, status, max_depth=max_depth)

            if len(replychain) < max_depth:
                tm.reply(status.id)

        else:
            tm.reply(status.id)


if __name__ == '__main__':
    main()
````

**Comment by BrekiTomasson** [comment]
Thanks! Had to make some modification to fit the way I use the config file (I have multiple config files for multiple bots but only one application, then scripts that call the different bots). Just one outstanding problem.

Traceback (most recent call last):
  File "./reply.py", line 42, in <module>
    main()
  File "./reply.py", line 24, in main
    max_depth = sys.argv[1]
NameError: global name 'sys' is not defined

**Comment by fitnr** [comment]
add `import sys` to the top
